build:
  image: default-bionic
  environment:
    php: 8.1.1
    node: 14
    hosts:
      laravel.dev: "127.0.0.1"
    variables:
      APP_KEY: "base64:OYl4Bk9ekouOUIRXyeTD0FVi+cJ9D+HMyDJBgSBSUuI="
      APP_ENV: "testing"
      APP_URL: "http://laravel.dev"
      API_HOST: "laravel.dev"
      DB_HOST: "127.0.0.1"
      DB_DATABASE: "scrutinizer"
      DB_USERNAME: "root"
      DB_PASSWORD: ""
      MAIL_DRIVER: "log"
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests-and-coverage:
      services:
        mysql: 5.7

      dependencies:
        override:
          - composer self-update
          - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
          - chmod -R 777 storage
          - chmod -R 777 bootstrap/cache
          - npm i
          - npm run production
      tests:
        before:
          - mysql -u root -e 'CREATE DATABASE scrutinizer'
          - php artisan migrate --seed
